/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SmartPrescriptionReaderIndexImport } from './routes/smartPrescriptionReader/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SmartPrescriptionReaderIndexRoute =
  SmartPrescriptionReaderIndexImport.update({
    id: '/smartPrescriptionReader/',
    path: '/smartPrescriptionReader/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/smartPrescriptionReader/': {
      id: '/smartPrescriptionReader/'
      path: '/smartPrescriptionReader'
      fullPath: '/smartPrescriptionReader'
      preLoaderRoute: typeof SmartPrescriptionReaderIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/smartPrescriptionReader': typeof SmartPrescriptionReaderIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/smartPrescriptionReader': typeof SmartPrescriptionReaderIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/smartPrescriptionReader/': typeof SmartPrescriptionReaderIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/smartPrescriptionReader'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/smartPrescriptionReader'
  id: '__root__' | '/' | '/smartPrescriptionReader/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SmartPrescriptionReaderIndexRoute: typeof SmartPrescriptionReaderIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SmartPrescriptionReaderIndexRoute: SmartPrescriptionReaderIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/smartPrescriptionReader/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/smartPrescriptionReader/": {
      "filePath": "smartPrescriptionReader/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
