projects:
  default:
    schema: src/schema/*.graphql
    documents: src/documents/**/*.graphql
    extensions:
      turms:
        out_dir: ../../core/smart_prescription_reader/models
        stylers:
          - type: turms.stylers.capitalize.CapitalizeStyler
          - type: turms.stylers.snake_case.SnakeCaseStyler
        processors:
          - type: turms.processors.black.BlackProcessor
          - type: turms.processors.isort.IsortProcessor
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
          - type: turms.plugins.objects.ObjectsPlugin
          - type: turms.plugins.operations.OperationsPlugin
        scalar_definitions:
          AWSDate: datetime.date
          AWSDateTime: datetime.datetime
          AWSEmail: str
          AWSTime: datetime.time
          AWSJSON: str
          AWSURL: str
          AWSPhone: str
          AWSIPAddress: str
          AWSTimestamp: datetime.datetime
